version: '3.3'
services:
  db:
    image: mongo:4.4.8-focal
    environment:
      - TZ=Australia/Melbourne
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017

volumes:
  db:
