services:
  db:
    image: mongo:4.4.8-focal
    environment:
      - TZ=Australia/Melbourne
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    networks:
      - custom_network

volumes:
  db:

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
